//default entry point for the game
//this file has been 90% generated by Phaser
var game;

window.onload = function() {
	game = new Phaser.Game(1024, 768, Phaser.AUTO, '', null, false, true, {"arcade":true});//use arcade physics (performance cost: medium)
	game.state.add("Menu", Menu);//load up the 2 levels
	game.state.add("Level", Level);
	game.state.start("Menu");//startup the menu
};